import type { Lang } from '../lib/i18n';
import { BRAND } from '../brand';

/**
 * Landing copy in all three languages, written per language rather than run
 * through the dashboard phrase tables — marketing text needs real wording.
 *
 * Comparison rows use 2 = yes, 1 = partly / some apps, 0 = no.
 */
const B = BRAND.name;

const ru = {
  meta: { title: `${B} — вся зарядка Узбекистана в одном приложении` },
  nav: {
    drivers: 'Водителям', business: 'Автопаркам', operators: 'Операторам', pricing: 'Тарифы',
    compare: 'Сравнение', faq: 'Вопросы', map: 'Сеть', join: 'Подключиться', demo: 'Открыть демо', download: 'Скачать', menu: 'Меню', close: 'Закрыть',
  },
  hero: {
    badge: 'Национальная сеть зарядки · запуск MVP — Q4 2026',
    title: ['Вся зарядка', 'Узбекистана.', 'В одном приложении.'],
    sub: 'Находите свободные станции любых операторов, запускайте зарядку с телефона и платите через Payme или Click. Ночью — на 30% дешевле.',
    primary: 'Попробовать демо',
    secondary: 'Как это работает',
    live: 'Live · демо-сеть',
    stations: 'станций',
    connectors: 'разъёмов',
    online: 'онлайн',
    energy: 'кВт·ч сегодня',
    scroll: 'Листайте',
  },
  cities: {
    tashkent: 'Ташкент', samarkand: 'Самарканд', bukhara: 'Бухара', khiva: 'Хива', nukus: 'Нукус',
    namangan: 'Наманган', andijan: 'Андижан', fergana: 'Фергана', navoi: 'Навои', karshi: 'Карши',
    termez: 'Термез', jizzakh: 'Джизак', gulistan: 'Гулистан', kokand: 'Коканд', urgench: 'Ургенч',
  },
  strip: { pay: 'Оплата', standards: 'Стандарты', langs: 'Языки' },
  problem: {
    kicker: 'Проблема',
    title: 'Сегодня у каждой сети — своё приложение.',
    sub: 'Водитель электромобиля в Узбекистане держит на телефоне несколько приложений, не знает, свободна ли станция, пока не доедет, и платит по-разному в каждой сети.',
    items: [
      { n: '5+', t: 'приложений', d: 'нужно установить, чтобы видеть все крупные сети страны' },
      { n: '?', t: 'свободно ли', d: 'статус разъёма часто узнаёшь только на месте' },
      { n: '0', t: 'общей очереди', d: 'кто первым подъехал, тот и зарядился — без правил' },
    ],
    answer: `${B} объединяет все сети в одной карте, одном кошельке и одной очереди.`,
  },
  how: {
    kicker: 'Как это работает',
    title: 'Три шага — и вы заряжаетесь.',
    steps: [
      { t: 'Найдите', d: 'Карта показывает станции всех операторов и живой статус каждого разъёма: свободен, занят, на обслуживании.' },
      { t: 'Подключите', d: 'Вставьте кабель и нажмите «Начать» в приложении — или забронируйте разъём заранее, чтобы его никто не занял.' },
      { t: 'Оплатите', d: 'Сумма списывается с кошелька по факту кВт·ч. Чек, история и экономия CO₂ — в профиле.' },
    ],
  },
  features: {
    kicker: 'Возможности',
    title: 'Всё, что нужно водителю. И чего нет у других.',
    sub: 'Каждая функция ниже уже работает в демо — откройте Driver App и проверьте сами.',
    items: [
      { id: 'map', t: 'Live-карта всех сетей', d: 'Статус каждого разъёма обновляется в реальном времени, без перезагрузки.' },
      { id: 'queue', t: 'Честная очередь', d: 'Все разъёмы заняты? Встаньте в очередь — освободившийся удержат за вами 5 минут.' },
      { id: 'book', t: 'Бронирование', d: 'За 10 минут или за сутки. 15 минут на подъезд, сбор 2 000 сум.' },
      { id: 'green', t: 'Зелёные часы', d: 'Ночью ×0.7, днём ×0.9, в вечерний пик ×1.25. Цена фиксируется в момент старта.' },
      { id: 'trip', t: 'Планировщик поездок', d: 'Маршрут между городами с остановками на зарядку под ваш автомобиль.' },
      { id: 'wallet', t: 'Payme и Click', d: 'Кошелёк пополняется только после подтверждения от платёжной системы.' },
      { id: 'push', t: 'Push-уведомления', d: 'Зарядка закончилась, подошла очередь, бронь скоро истечёт — сообщим.' },
      { id: 'eco', t: 'Эко-профиль', d: 'Сэкономленный CO₂ в деревьях и километрах, достижения и рейтинг.' },
      { id: 'report', t: 'Жалоба в один тап', d: 'Сломан разъём? Оповещение сразу уходит оператору именно этой станции.' },
      { id: 'lang', t: 'UZ · RU · EN', d: 'Полностью на трёх языках. Работает офлайн как приложение (PWA).' },
    ],
  },
  network: {
    kicker: 'Сеть сейчас',
    title: 'Живые данные прямо со станций.',
    sub: 'Статусы разъёмов приходят с сервера в реальном времени. Начните зарядку в демо — и через секунду увидите её здесь.',
    filters: { all: 'Все', free: 'Есть свободные', fast: 'Быстрые DC' },
    freeOf: 'свободно',
    perKwh: 'сум/кВт·ч',
    feed: 'Лента событий',
    empty: 'Пока тихо. Начните зарядку в Driver App — событие появится здесь.',
    ev: { start: 'Началась зарядка', stop: 'Разъём освободился', reserved: 'Разъём забронирован', offline: 'Разъём недоступен' },
    status: { available: 'свободен', occupied: 'занят', reserved: 'бронь', unavailable: 'недоступен' },
    open: 'Зарядиться здесь',
    none: 'Нет станций под этот фильтр.',
    meta: 'Единая платформа зарядки электромобилей в Узбекистане: станции всех операторов, оплата через Payme и Click, очередь и бронирование.',
  },
  green: {
    kicker: 'Зелёные часы',
    title: 'Заряжайтесь ночью — платите на 30% меньше.',
    sub: 'Цена зависит от часа по Ташкенту и фиксируется в момент старта. График ниже — живые данные сервера.',
    now: 'Сейчас',
    best: 'Самое дешёвое окно',
    in: 'через',
    h: 'ч',
    active: 'уже действует',
    bands: { green: 'Ночь ×0.7', day: 'День ×0.9', standard: 'Обычный ×1.0', peak: 'Пик ×1.25' },
  },
  calc: {
    kicker: 'Калькулятор',
    title: 'Сколько вы сэкономите на электромобиле.',
    sub: 'Подставьте свой пробег. Цены — оценка, их можно поменять.',
    car: 'Автомобиль',
    km: 'Пробег в месяц, км',
    petrol: 'Бензин, сум/л',
    kwh: 'Зарядка, сум/кВт·ч',
    night: 'Заряжаться ночью',
    evMonth: 'Электричество в месяц',
    petrolMonth: 'Бензин в месяц',
    save: 'Экономия за год',
    full: 'Полный заряд',
    range: 'Запас хода',
    sum: 'сум',
    km_: 'км',
    note: 'Расход бензиновой машины — 8 л/100 км. Расход и батарея ЭВ — средние паспортные данные, на трассе и зимой выше.',
  },
  compare: {
    kicker: 'Сравнение',
    title: 'Почему не обычное приложение сети.',
    sub: 'Сравниваем с типичными решениями по категориям, а не с конкретными компаниями.',
    cols: [B, 'Приложение одной сети', 'Карта-агрегатор'],
    rows: [
      { t: 'Станции всех операторов страны', v: [2, 0, 2] },
      { t: 'Запуск и оплата зарядки в приложении', v: [2, 2, 0] },
      { t: 'Живой статус каждого разъёма', v: [2, 2, 1] },
      { t: 'Бронирование разъёма', v: [2, 1, 0] },
      { t: 'Общая очередь к станции', v: [2, 0, 0] },
      { t: 'Ночной тариф и подсказка, когда дешевле', v: [2, 0, 0] },
      { t: 'Маршрут между городами с остановками', v: [2, 1, 2] },
      { t: 'Payme и Click', v: [2, 1, 0] },
      { t: 'Кабинет для корпоративного автопарка', v: [2, 0, 0] },
      { t: 'Открытый API и вебхуки для партнёров', v: [2, 0, 1] },
      { t: 'Полностью на узбекском, русском и английском', v: [2, 1, 1] },
    ],
    legend: ['есть', 'частично', 'нет'],
  },
  audiences: {
    kicker: 'Платформа',
    title: 'Одна система для всех участников рынка.',
    sub: 'Шесть приложений работают на одной базе и синхронизируются мгновенно: действие водителя сразу видят оператор, компания и администратор.',
    open: 'Открыть демо',
    tabs: [
      {
        id: 'driver', label: 'Водителям', title: 'Driver App', portal: 'driver',
        d: 'Мобильное приложение для iOS и Android: карта, зарядка, очередь, бронь, кошелёк, поездки.',
        points: ['Вход по SMS-коду', 'Карта всех сетей с фильтрами', 'Удалённый старт и стоп', 'История и чеки', 'Эко-профиль и достижения'],
      },
      {
        id: 'business', label: 'Автопаркам', title: 'Business Portal', portal: 'business',
        d: 'Для такси, доставки и корпоративных парков: один счёт на все машины и лимиты на сотрудников.',
        points: ['Автомобили и водители', 'Лимиты по сумме и кВт·ч', 'Расходы по машинам и отделам', 'Отчёты CSV и PDF', 'Двухфакторный вход'],
      },
      {
        id: 'operator', label: 'Операторам', title: 'Operator Portal', portal: 'operator',
        d: 'Для владельцев станций: подключите зарядки по OCPP и получите водителей всей страны.',
        points: ['OCPP 1.6-J из коробки', 'Станции, разъёмы, сессии live', 'Тарифы и зелёные часы', 'Оповещения и жалобы водителей', 'Финансы и выплаты'],
      },
      {
        id: 'api', label: 'Разработчикам', title: 'Partner API', portal: 'api',
        d: 'REST API, вебхуки с HMAC-подписью и песочница — для ТЦ, отелей, навигаторов и автодилеров.',
        points: ['Документация и песочница', 'Вебхуки с повторами', 'Журнал доставок', 'Ключи и права доступа', 'Тестовый режим'],
      },
    ],
    admin: 'Плюс Admin Control Center — национальный мониторинг, платежи, фрод и аудит.',
  },
  route: {
    kicker: 'Поездки',
    title: 'Ташкент → Хива без страха разрядиться.',
    sub: 'Пример маршрута по Великому шёлковому пути на Zeekr 001. Планировщик сам подберёт станции и время зарядки.',
    stops: [
      { city: 'Ташкент', km: 0, note: 'Старт · 100%' },
      { city: 'Самарканд', km: 305, note: 'Зарядка 20 мин' },
      { city: 'Бухара', km: 575, note: 'Зарядка 35 мин' },
      { city: 'Хива', km: 1020, note: 'Финиш · 20%' },
    ],
    total: 'около 1 020 км · 2 остановки',
  },
  security: {
    kicker: 'Надёжность',
    title: 'Деньги и данные под защитой.',
    items: [
      { t: 'Пароли и 2FA', d: 'Пароли хранятся как scrypt-хеши. Двухфакторный вход совместим с Google Authenticator.' },
      { t: 'Оплата без карт у нас', d: 'Данные карты вводятся на стороне Payme или Click. Кошелёк пополняется только после их подтверждения.' },
      { t: 'SMS-коды', d: 'Коды хранятся хешированными, живут 5 минут и дают 5 попыток. Есть лимиты на номер.' },
      { t: 'Подписанные вебхуки', d: 'Каждое событие партнёру подписано HMAC-SHA256, внутренние адреса запрещены.' },
      { t: 'Раздельный доступ', d: 'У каждого портала свой вход. Оператор видит только свою сеть, компания — только свой парк.' },
      { t: 'Данные в Узбекистане', d: 'К запуску — серверы в Узбекистане, как требует закон о персональных данных.' },
    ],
  },
  roadmap: {
    kicker: 'Дорожная карта',
    title: 'От MVP до всей Центральной Азии.',
    done: 'Готово',
    items: [
      { when: 'Сентябрь 2026', t: 'Платформа', d: 'Шесть порталов, OCPP 1.6-J, Payme и Click, вход по SMS, push.', done: true },
      { when: 'Q4 2026', t: 'Запуск MVP', d: 'Ташкент, первые операторы, App Store и Google Play.' },
      { when: 'Q1 2027', t: 'Трасса М-37', d: 'Ташкент — Самарканд — Бухара, корпоративные автопарки.' },
      { when: 'Q2 2027', t: 'Роуминг', d: 'OCPP 2.0.1 и OCPI 2.3: одна зарядка во всех сетях без отдельных договоров.' },
      { when: 'H2 2027', t: 'Plug & Charge', d: 'ISO 15118: вставил кабель — зарядка началась и оплатилась сама.' },
      { when: '2028', t: 'Центральная Азия', d: 'Казахстан, Кыргызстан, Таджикистан — один аккаунт на весь регион.' },
    ],
  },
  app: {
    kicker: 'Приложение',
    title: 'Скоро в App Store и Google Play.',
    sub: 'А пока откройте полноценное демо прямо в браузере — оно работает на настоящем сервере.',
    soon: 'Скоро',
    web: 'Открыть в браузере',
  },
  join: {
    kicker: 'Подключиться',
    title: 'Будьте с нами с первого дня.',
    sub: 'Оставьте контакт — водителям сообщим о запуске, операторам и компаниям перезвоним в течение рабочего дня.',
    tabs: { driver: 'Водителям', operator: 'Операторам станций', fleet: 'Автопаркам', partner: 'Партнёрам' },
    pitch: {
      driver: 'Сообщим о запуске в числе первых и откроем ранний доступ к приложению.',
      operator: 'Подключите станции по OCPP 1.6-J и получите водителей со всей страны.',
      fleet: 'Один счёт на все машины и лимиты для водителей — расскажем, как перевести парк.',
      partner: 'ТЦ, отели, автодилеры, навигаторы — зарядка на вашей площадке или в вашем приложении.',
    },
    name: 'Имя',
    phone: 'Телефон',
    company: 'Компания',
    city: 'Город',
    size: { operator: 'Сколько станций', fleet: 'Сколько машин', partner: 'Что предлагаете' },
    message: 'Комментарий',
    optional: 'необязательно',
    consent: 'Я согласен на обработку персональных данных согласно',
    consentLink: 'политике конфиденциальности',
    submit: { driver: 'Сообщить мне о запуске', other: 'Отправить заявку' },
    sending: 'Отправляем…',
    done: 'Спасибо! Заявка принята.',
    doneDriver: 'Мы пришлём SMS в день запуска.',
    doneOther: 'Перезвоним в течение рабочего дня.',
    again: 'Отправить ещё одну',
    already: 'Этот номер уже есть в списке — мы с вами свяжемся.',
    errors: { phone: 'Введите номер в формате +998 XX XXX XX XX', name: 'Укажите имя', company: 'Укажите компанию', consent: 'Нужно согласие на обработку данных', rate: 'Слишком много заявок — попробуйте через несколько минут', generic: 'Не получилось отправить — проверьте соединение и попробуйте ещё раз' },
  },
  legal: {
    privacy: 'Политика конфиденциальности', terms: 'Условия использования', offer: 'Публичная оферта',
    title: 'Документы', back: 'На главную', updated: 'Редакция от',
    draft: 'Черновик. Документ готовится к публикации и проверяется юристом — до этого он не является действующей редакцией.',
    ruOnly: '',
  },
  faq: {
    kicker: 'Вопросы',
    title: 'Частые вопросы.',
    items: [
      { q: `Что такое ${B}?`, a: `${B} — единая платформа зарядки электромобилей в Узбекистане. Мы не строим свои станции, а объединяем сети разных операторов в одном приложении: карта, запуск, оплата и очередь работают одинаково везде.` },
      { q: 'Сколько стоит зарядка?', a: 'Базовую цену за кВт·ч ставит оператор станции, вы видите её до старта. Ночью (23:00–07:00) цена ×0.7, днём ×0.9, в вечерний пик ×1.25 — множитель фиксируется в момент начала зарядки.' },
      { q: 'Как оплатить?', a: 'Пополните кошелёк через Payme или Click — картой Humo, Uzcard или другой, которую принимает платёжная система. Деньги зачисляются только после подтверждения платежа, зарядка списывается по факту кВт·ч.' },
      { q: 'Что если все разъёмы заняты?', a: 'Встаньте в очередь в приложении. Когда разъём освободится, мы удержим его за вами 5 минут и пришлём уведомление — занять его другой водитель не сможет.' },
      { q: 'Можно забронировать разъём заранее?', a: 'Да: от 10 минут до 24 часов вперёд. У вас будет 15 минут на подъезд, сбор за бронь — 2 000 сум. Неиспользованная бронь истекает сама.' },
      { q: 'Подойдёт ли моя машина?', a: 'Приложение показывает тип и мощность каждого разъёма, а фильтр оставит только подходящие станции. Для поездок планировщик учитывает батарею и расход вашей модели.' },
      { q: 'Я владелец станций. Как подключиться?', a: 'Станции подключаются по OCPP 1.6-J — это стандарт большинства зарядок. Вы получаете кабинет оператора: сессии, тарифы, оповещения, финансы. Водители всей страны видят ваши станции сразу.' },
      { q: 'Есть ли решение для компаний?', a: 'Business Portal: один счёт на все машины, лимиты на сотрудников по сумме и кВт·ч, отчёты по расходам в CSV и PDF.' },
      { q: 'Когда запуск?', a: 'Запуск MVP в Ташкенте запланирован на Q4 2026. Демо со всеми функциями уже работает — его можно открыть с этой страницы.' },
    ],
  },
  cta: {
    title: 'Попробуйте прямо сейчас.',
    sub: 'Демо работает на настоящем сервере: начните зарядку в Driver App и посмотрите, как она появится у оператора.',
    button: 'Открыть демо',
    compare: 'Два портала рядом',
  },
  phone: { free: 'свободно', start: 'Начать зарядку', charging: 'Зарядка', added: 'кВт·ч', cost: 'сум', left: 'мин до 80%', near: 'Рядом с вами', kw: 'кВт' },
  footer: {
    about: 'Единая платформа зарядки электромобилей. Сделано в Узбекистане.',
    product: 'Продукт',
    platform: 'Платформа',
    company: 'Компания',
    links: {
      drivers: 'Водителям', business: 'Автопаркам', operators: 'Операторам', api: 'API для партнёров',
      arch: 'Архитектура', roadmap: 'Дорожная карта', security: 'Безопасность', faq: 'Вопросы', contact: 'Связаться',
    },
    rights: 'Все права защищены.',
    demo: 'Демо-версия: цифры на странице берутся из демо-базы.',
  },
};

export type LandingCopy = typeof ru;

const uz: LandingCopy = {
  meta: { title: `${B} — O‘zbekistondagi barcha zaryadlash bitta ilovada` },
  nav: {
    drivers: 'Haydovchilarga', business: 'Avtoparklarga', operators: 'Operatorlarga', pricing: 'Tariflar',
    compare: 'Taqqoslash', faq: 'Savollar', map: 'Tarmoq', join: 'Ulanish', demo: 'Demoni ochish', download: 'Yuklab olish', menu: 'Menyu', close: 'Yopish',
  },
  hero: {
    badge: 'Milliy zaryadlash tarmog‘i · MVP ishga tushishi — 2026-yil IV chorak',
    title: ['O‘zbekistondagi', 'barcha zaryadlash.', 'Bitta ilovada.'],
    sub: 'Istalgan operatorning bo‘sh stansiyalarini toping, zaryadlashni telefondan boshlang va Payme yoki Click orqali to‘lang. Tunda — 30% arzonroq.',
    primary: 'Demoni sinab ko‘ring',
    secondary: 'Qanday ishlaydi',
    live: 'Live · demo tarmoq',
    stations: 'stansiya',
    connectors: 'ulagich',
    online: 'onlayn',
    energy: 'kVt·s bugun',
    scroll: 'Pastga',
  },
  cities: {
    tashkent: 'Toshkent', samarkand: 'Samarqand', bukhara: 'Buxoro', khiva: 'Xiva', nukus: 'Nukus',
    namangan: 'Namangan', andijan: 'Andijon', fergana: 'Farg‘ona', navoi: 'Navoiy', karshi: 'Qarshi',
    termez: 'Termiz', jizzakh: 'Jizzax', gulistan: 'Guliston', kokand: 'Qo‘qon', urgench: 'Urganch',
  },
  strip: { pay: 'To‘lov', standards: 'Standartlar', langs: 'Tillar' },
  problem: {
    kicker: 'Muammo',
    title: 'Bugun har bir tarmoqning o‘z ilovasi bor.',
    sub: 'O‘zbekistondagi elektromobil haydovchisi telefonida bir nechta ilova saqlaydi, stansiya bo‘shligini yetib bormaguncha bilmaydi va har bir tarmoqda turlicha to‘laydi.',
    items: [
      { n: '5+', t: 'ilova', d: 'mamlakatdagi barcha yirik tarmoqlarni ko‘rish uchun o‘rnatish kerak' },
      { n: '?', t: 'bo‘shmi', d: 'ulagich holatini ko‘pincha faqat joyida bilasiz' },
      { n: '0', t: 'umumiy navbat', d: 'kim birinchi kelsa, o‘sha zaryadlaydi — qoidasiz' },
    ],
    answer: `${B} barcha tarmoqlarni bitta xarita, bitta hamyon va bitta navbatga birlashtiradi.`,
  },
  how: {
    kicker: 'Qanday ishlaydi',
    title: 'Uch qadam — va zaryadlanyapsiz.',
    steps: [
      { t: 'Toping', d: 'Xarita barcha operatorlarning stansiyalarini va har bir ulagichning jonli holatini ko‘rsatadi: bo‘sh, band, ta’mirda.' },
      { t: 'Ulang', d: 'Kabelni ulang va ilovada «Boshlash»ni bosing — yoki ulagichni oldindan band qiling, uni hech kim egallamaydi.' },
      { t: 'To‘lang', d: 'Summa hamyondan haqiqiy kVt·s bo‘yicha yechiladi. Chek, tarix va CO₂ tejamkorligi — profilda.' },
    ],
  },
  features: {
    kicker: 'Imkoniyatlar',
    title: 'Haydovchiga kerak bo‘lgan hamma narsa. Boshqalarda yo‘q narsalar ham.',
    sub: 'Quyidagi har bir funksiya demoda allaqachon ishlaydi — Driver App’ni oching va o‘zingiz tekshiring.',
    items: [
      { id: 'map', t: 'Barcha tarmoqlarning jonli xaritasi', d: 'Har bir ulagich holati sahifani yangilamasdan real vaqtda yangilanadi.' },
      { id: 'queue', t: 'Adolatli navbat', d: 'Hamma ulagichlar bandmi? Navbatga turing — bo‘shagan ulagich 5 daqiqa siz uchun saqlanadi.' },
      { id: 'book', t: 'Band qilish', d: '10 daqiqa yoki bir sutka oldin. Yetib kelish uchun 15 daqiqa, yig‘im 2 000 so‘m.' },
      { id: 'green', t: 'Yashil soatlar', d: 'Tunda ×0.7, kunduzi ×0.9, kechki cho‘qqida ×1.25. Narx boshlanish paytida qayd etiladi.' },
      { id: 'trip', t: 'Sayohat rejalashtiruvchi', d: 'Shaharlararo marshrut — avtomobilingizga mos zaryadlash to‘xtashlari bilan.' },
      { id: 'wallet', t: 'Payme va Click', d: 'Hamyon faqat to‘lov tizimi tasdiqlagandan keyin to‘ldiriladi.' },
      { id: 'push', t: 'Push-bildirishnomalar', d: 'Zaryadlash tugadi, navbatingiz keldi, bron muddati tugayapti — xabar beramiz.' },
      { id: 'eco', t: 'Eko-profil', d: 'Tejalgan CO₂ daraxt va kilometrlarda, yutuqlar va reyting.' },
      { id: 'report', t: 'Bir bosishda shikoyat', d: 'Ulagich buzilganmi? Ogohlantirish darhol aynan shu stansiya operatoriga boradi.' },
      { id: 'lang', t: 'UZ · RU · EN', d: 'To‘liq uch tilda. Oflayn ilova sifatida ishlaydi (PWA).' },
    ],
  },
  network: {
    kicker: 'Tarmoq hozir',
    title: 'Stansiyalardan to‘g‘ridan-to‘g‘ri jonli ma’lumotlar.',
    sub: 'Ulagichlar holati serverdan real vaqtda keladi. Demoda zaryadlashni boshlang — bir soniyada uni shu yerda ko‘rasiz.',
    filters: { all: 'Barchasi', free: 'Bo‘shi bor', fast: 'Tezkor DC' },
    freeOf: 'bo‘sh',
    perKwh: 'so‘m/kVt·s',
    feed: 'Hodisalar lentasi',
    empty: 'Hozircha tinch. Driver App’da zaryadlashni boshlang — hodisa shu yerda paydo bo‘ladi.',
    ev: { start: 'Zaryadlash boshlandi', stop: 'Ulagich bo‘shadi', reserved: 'Ulagich band qilindi', offline: 'Ulagich ishlamayapti' },
    status: { available: 'bo‘sh', occupied: 'band', reserved: 'bron', unavailable: 'ishlamaydi' },
    open: 'Shu yerda zaryadlash',
    none: 'Bu filtrga mos stansiya yo‘q.',
    meta: 'O‘zbekistondagi yagona elektromobil zaryadlash platformasi: barcha operatorlar stansiyalari, Payme va Click orqali to‘lov, navbat va bron.',
  },
  green: {
    kicker: 'Yashil soatlar',
    title: 'Tunda zaryadlang — 30% kam to‘lang.',
    sub: 'Narx Toshkent vaqti bo‘yicha soatga bog‘liq va boshlanish paytida qayd etiladi. Quyidagi grafik — serverning jonli ma’lumotlari.',
    now: 'Hozir',
    best: 'Eng arzon vaqt',
    in: '',
    h: 'soatdan keyin',
    active: 'hozir amalda',
    bands: { green: 'Tun ×0.7', day: 'Kun ×0.9', standard: 'Oddiy ×1.0', peak: 'Cho‘qqi ×1.25' },
  },
  calc: {
    kicker: 'Kalkulyator',
    title: 'Elektromobilda qancha tejaysiz.',
    sub: 'O‘z yurgan masofangizni kiriting. Narxlar — taxminiy, ularni o‘zgartirish mumkin.',
    car: 'Avtomobil',
    km: 'Oylik masofa, km',
    petrol: 'Benzin, so‘m/l',
    kwh: 'Zaryadlash, so‘m/kVt·s',
    night: 'Tunda zaryadlash',
    evMonth: 'Oyiga elektr',
    petrolMonth: 'Oyiga benzin',
    save: 'Yillik tejash',
    full: 'To‘liq zaryad',
    range: 'Yurish zaxirasi',
    sum: 'so‘m',
    km_: 'km',
    note: 'Benzinli mashina sarfi — 100 km ga 8 l. EV sarfi va batareyasi — o‘rtacha pasport ma’lumotlari, trassada va qishda yuqoriroq.',
  },
  compare: {
    kicker: 'Taqqoslash',
    title: 'Nega oddiy tarmoq ilovasi emas.',
    sub: 'Aniq kompaniyalar bilan emas, odatiy yechimlar toifalari bilan taqqoslaymiz.',
    cols: [B, 'Bitta tarmoq ilovasi', 'Agregator-xarita'],
    rows: [
      { t: 'Mamlakatdagi barcha operatorlar stansiyalari', v: [2, 0, 2] },
      { t: 'Ilovada zaryadlashni boshlash va to‘lash', v: [2, 2, 0] },
      { t: 'Har bir ulagichning jonli holati', v: [2, 2, 1] },
      { t: 'Ulagichni band qilish', v: [2, 1, 0] },
      { t: 'Stansiyaga umumiy navbat', v: [2, 0, 0] },
      { t: 'Tungi tarif va qachon arzonligi haqida maslahat', v: [2, 0, 0] },
      { t: 'To‘xtashlar bilan shaharlararo marshrut', v: [2, 1, 2] },
      { t: 'Payme va Click', v: [2, 1, 0] },
      { t: 'Korporativ avtopark kabineti', v: [2, 0, 0] },
      { t: 'Hamkorlar uchun ochiq API va vebhuklar', v: [2, 0, 1] },
      { t: 'To‘liq o‘zbek, rus va ingliz tillarida', v: [2, 1, 1] },
    ],
    legend: ['bor', 'qisman', 'yo‘q'],
  },
  audiences: {
    kicker: 'Platforma',
    title: 'Bozorning barcha ishtirokchilari uchun bitta tizim.',
    sub: 'Oltita ilova bitta bazada ishlaydi va bir zumda sinxronlanadi: haydovchining harakatini operator, kompaniya va administrator darhol ko‘radi.',
    open: 'Demoni ochish',
    tabs: [
      {
        id: 'driver', label: 'Haydovchilarga', title: 'Driver App', portal: 'driver',
        d: 'iOS va Android uchun mobil ilova: xarita, zaryadlash, navbat, bron, hamyon, sayohatlar.',
        points: ['SMS-kod orqali kirish', 'Filtrlar bilan barcha tarmoqlar xaritasi', 'Masofadan boshlash va to‘xtatish', 'Tarix va cheklar', 'Eko-profil va yutuqlar'],
      },
      {
        id: 'business', label: 'Avtoparklarga', title: 'Business Portal', portal: 'business',
        d: 'Taksi, yetkazib berish va korporativ parklar uchun: barcha mashinalarga bitta hisob va xodimlarga limitlar.',
        points: ['Avtomobillar va haydovchilar', 'Summa va kVt·s bo‘yicha limitlar', 'Mashina va bo‘limlar bo‘yicha xarajatlar', 'CSV va PDF hisobotlar', 'Ikki bosqichli kirish'],
      },
      {
        id: 'operator', label: 'Operatorlarga', title: 'Operator Portal', portal: 'operator',
        d: 'Stansiya egalari uchun: zaryadlagichlarni OCPP orqali ulang va butun mamlakat haydovchilarini oling.',
        points: ['Tayyor OCPP 1.6-J', 'Stansiyalar, ulagichlar, seanslar live', 'Tariflar va yashil soatlar', 'Ogohlantirishlar va shikoyatlar', 'Moliya va to‘lovlar'],
      },
      {
        id: 'api', label: 'Dasturchilarga', title: 'Partner API', portal: 'api',
        d: 'REST API, HMAC imzoli vebhuklar va sinov muhiti — savdo markazlari, mehmonxonalar, navigatorlar va dilerlar uchun.',
        points: ['Hujjatlar va sinov muhiti', 'Qayta urinishli vebhuklar', 'Yetkazish jurnali', 'Kalitlar va ruxsatlar', 'Test rejimi'],
      },
    ],
    admin: 'Va Admin Control Center — milliy monitoring, to‘lovlar, firibgarlik va audit.',
  },
  route: {
    kicker: 'Sayohatlar',
    title: 'Toshkent → Xiva — zaryad tugashidan qo‘rqmasdan.',
    sub: 'Zeekr 001’da Buyuk ipak yo‘li bo‘ylab marshrut namunasi. Rejalashtiruvchi stansiyalar va zaryadlash vaqtini o‘zi tanlaydi.',
    stops: [
      { city: 'Toshkent', km: 0, note: 'Start · 100%' },
      { city: 'Samarqand', km: 305, note: 'Zaryadlash 20 daq' },
      { city: 'Buxoro', km: 575, note: 'Zaryadlash 35 daq' },
      { city: 'Xiva', km: 1020, note: 'Finish · 20%' },
    ],
    total: 'taxminan 1 020 km · 2 ta to‘xtash',
  },
  security: {
    kicker: 'Ishonchlilik',
    title: 'Pul va ma’lumotlar himoyada.',
    items: [
      { t: 'Parollar va 2FA', d: 'Parollar scrypt-xesh sifatida saqlanadi. Ikki bosqichli kirish Google Authenticator bilan mos.' },
      { t: 'Karta ma’lumotlari bizda emas', d: 'Karta Payme yoki Click tomonida kiritiladi. Hamyon faqat ular tasdiqlagandan keyin to‘ldiriladi.' },
      { t: 'SMS-kodlar', d: 'Kodlar xeshlangan holda saqlanadi, 5 daqiqa amal qiladi va 5 ta urinish beradi. Raqamga limitlar bor.' },
      { t: 'Imzolangan vebhuklar', d: 'Hamkorga har bir hodisa HMAC-SHA256 bilan imzolanadi, ichki manzillar taqiqlangan.' },
      { t: 'Alohida kirish', d: 'Har bir portalning o‘z kirishi bor. Operator faqat o‘z tarmog‘ini, kompaniya faqat o‘z parkini ko‘radi.' },
      { t: 'Ma’lumotlar O‘zbekistonda', d: 'Ishga tushishga qadar — shaxsiy ma’lumotlar to‘g‘risidagi qonun talabiga ko‘ra O‘zbekistondagi serverlar.' },
    ],
  },
  roadmap: {
    kicker: 'Yo‘l xaritasi',
    title: 'MVP’dan butun Markaziy Osiyogacha.',
    done: 'Tayyor',
    items: [
      { when: '2026-yil sentabr', t: 'Platforma', d: 'Oltita portal, OCPP 1.6-J, Payme va Click, SMS orqali kirish, push.', done: true },
      { when: '2026 IV chorak', t: 'MVP ishga tushishi', d: 'Toshkent, birinchi operatorlar, App Store va Google Play.' },
      { when: '2027 I chorak', t: 'M-37 trassasi', d: 'Toshkent — Samarqand — Buxoro, korporativ avtoparklar.' },
      { when: '2027 II chorak', t: 'Rouming', d: 'OCPP 2.0.1 va OCPI 2.3: alohida shartnomalarsiz barcha tarmoqlarda bitta zaryadlash.' },
      { when: '2027 II yarim', t: 'Plug & Charge', d: 'ISO 15118: kabelni uladingiz — zaryadlash boshlandi va o‘zi to‘landi.' },
      { when: '2028', t: 'Markaziy Osiyo', d: 'Qozog‘iston, Qirg‘iziston, Tojikiston — butun mintaqa uchun bitta akkaunt.' },
    ],
  },
  app: {
    kicker: 'Ilova',
    title: 'Tez orada App Store va Google Play’da.',
    sub: 'Hozircha to‘liq demoni to‘g‘ridan-to‘g‘ri brauzerda oching — u haqiqiy serverda ishlaydi.',
    soon: 'Tez orada',
    web: 'Brauzerda ochish',
  },
  join: {
    kicker: 'Ulanish',
    title: 'Birinchi kundan biz bilan bo‘ling.',
    sub: 'Kontaktingizni qoldiring — haydovchilarga ishga tushish haqida xabar beramiz, operatorlar va kompaniyalarga ish kuni davomida qo‘ng‘iroq qilamiz.',
    tabs: { driver: 'Haydovchilarga', operator: 'Stansiya operatorlariga', fleet: 'Avtoparklarga', partner: 'Hamkorlarga' },
    pitch: {
      driver: 'Ishga tushish haqida birinchilardan bo‘lib xabar beramiz va ilovaga erta kirish ochamiz.',
      operator: 'Stansiyalarni OCPP 1.6-J orqali ulang va butun mamlakat haydovchilarini oling.',
      fleet: 'Barcha mashinalar uchun bitta hisob va haydovchilarga limitlar — parkni qanday o‘tkazishni aytib beramiz.',
      partner: 'Savdo markazlari, mehmonxonalar, dilerlar, navigatorlar — maydoningizda yoki ilovangizda zaryadlash.',
    },
    name: 'Ism',
    phone: 'Telefon',
    company: 'Kompaniya',
    city: 'Shahar',
    size: { operator: 'Nechta stansiya', fleet: 'Nechta mashina', partner: 'Nima taklif qilasiz' },
    message: 'Izoh',
    optional: 'ixtiyoriy',
    consent: 'Shaxsiy ma’lumotlarimni qayta ishlashga roziman:',
    consentLink: 'maxfiylik siyosati',
    submit: { driver: 'Ishga tushganda xabar bering', other: 'Ariza yuborish' },
    sending: 'Yuborilmoqda…',
    done: 'Rahmat! Ariza qabul qilindi.',
    doneDriver: 'Ishga tushgan kuni SMS yuboramiz.',
    doneOther: 'Ish kuni davomida qo‘ng‘iroq qilamiz.',
    again: 'Yana bitta yuborish',
    already: 'Bu raqam ro‘yxatda bor — siz bilan bog‘lanamiz.',
    errors: { phone: 'Raqamni +998 XX XXX XX XX formatida kiriting', name: 'Ismingizni kiriting', company: 'Kompaniyani kiriting', consent: 'Ma’lumotlarni qayta ishlashga rozilik kerak', rate: 'Arizalar juda ko‘p — bir necha daqiqadan keyin urinib ko‘ring', generic: 'Yuborib bo‘lmadi — internetni tekshirib, qayta urinib ko‘ring' },
  },
  legal: {
    privacy: 'Maxfiylik siyosati', terms: 'Foydalanish shartlari', offer: 'Ommaviy oferta',
    title: 'Hujjatlar', back: 'Bosh sahifaga', updated: 'Tahrir sanasi',
    draft: 'Qoralama. Hujjat nashrga tayyorlanmoqda va yurist tomonidan tekshirilmoqda — shu paytgacha u amaldagi tahrir hisoblanmaydi.',
    ruOnly: 'Hujjat hozircha rus tilida. O‘zbek tilidagi tarjimasi nashrdan oldin qo‘shiladi.',
  },
  faq: {
    kicker: 'Savollar',
    title: 'Ko‘p beriladigan savollar.',
    items: [
      { q: `${B} nima?`, a: `${B} — O‘zbekistondagi yagona elektromobil zaryadlash platformasi. Biz o‘z stansiyalarimizni qurmaymiz, balki turli operatorlar tarmoqlarini bitta ilovaga birlashtiramiz: xarita, boshlash, to‘lov va navbat hamma joyda bir xil ishlaydi.` },
      { q: 'Zaryadlash qancha turadi?', a: 'kVt·s uchun asosiy narxni stansiya operatori belgilaydi, uni boshlashdan oldin ko‘rasiz. Tunda (23:00–07:00) narx ×0.7, kunduzi ×0.9, kechki cho‘qqida ×1.25 — koeffitsient zaryadlash boshlangan paytda qayd etiladi.' },
      { q: 'Qanday to‘lash mumkin?', a: 'Hamyonni Payme yoki Click orqali to‘ldiring — Humo, Uzcard yoki to‘lov tizimi qabul qiladigan boshqa karta bilan. Pul faqat to‘lov tasdiqlangandan keyin tushadi, zaryadlash haqiqiy kVt·s bo‘yicha yechiladi.' },
      { q: 'Hamma ulagichlar band bo‘lsa-chi?', a: 'Ilovada navbatga turing. Ulagich bo‘shaganda uni 5 daqiqa siz uchun saqlaymiz va bildirishnoma yuboramiz — boshqa haydovchi uni egallay olmaydi.' },
      { q: 'Ulagichni oldindan band qilsa bo‘ladimi?', a: 'Ha: 10 daqiqadan 24 soatgacha oldin. Yetib kelish uchun 15 daqiqa beriladi, bron yig‘imi — 2 000 so‘m. Foydalanilmagan bron o‘zi tugaydi.' },
      { q: 'Mashinam mos keladimi?', a: 'Ilova har bir ulagichning turi va quvvatini ko‘rsatadi, filtr esa faqat mos stansiyalarni qoldiradi. Sayohatlar uchun rejalashtiruvchi modelingiz batareyasi va sarfini hisobga oladi.' },
      { q: 'Men stansiya egasiman. Qanday ulanaman?', a: 'Stansiyalar OCPP 1.6-J orqali ulanadi — bu ko‘pchilik zaryadlagichlarning standarti. Siz operator kabinetini olasiz: seanslar, tariflar, ogohlantirishlar, moliya. Butun mamlakat haydovchilari stansiyalaringizni darhol ko‘radi.' },
      { q: 'Kompaniyalar uchun yechim bormi?', a: 'Business Portal: barcha mashinalar uchun bitta hisob, xodimlarga summa va kVt·s bo‘yicha limitlar, CSV va PDF xarajat hisobotlari.' },
      { q: 'Qachon ishga tushadi?', a: 'Toshkentda MVP 2026-yil IV choragida ishga tushishi rejalashtirilgan. Barcha funksiyalarga ega demo allaqachon ishlayapti — uni shu sahifadan ochish mumkin.' },
    ],
  },
  cta: {
    title: 'Hozirning o‘zida sinab ko‘ring.',
    sub: 'Demo haqiqiy serverda ishlaydi: Driver App’da zaryadlashni boshlang va u operatorda qanday paydo bo‘lishini ko‘ring.',
    button: 'Demoni ochish',
    compare: 'Ikki portal yonma-yon',
  },
  phone: { free: 'bo‘sh', start: 'Zaryadlashni boshlash', charging: 'Zaryadlash', added: 'kVt·s', cost: 'so‘m', left: 'daq 80% gacha', near: 'Yaqiningizda', kw: 'kVt' },
  footer: {
    about: 'Elektromobillar uchun yagona zaryadlash platformasi. O‘zbekistonda yaratilgan.',
    product: 'Mahsulot',
    platform: 'Platforma',
    company: 'Kompaniya',
    links: {
      drivers: 'Haydovchilarga', business: 'Avtoparklarga', operators: 'Operatorlarga', api: 'Hamkorlar uchun API',
      arch: 'Arxitektura', roadmap: 'Yo‘l xaritasi', security: 'Xavfsizlik', faq: 'Savollar', contact: 'Bog‘lanish',
    },
    rights: 'Barcha huquqlar himoyalangan.',
    demo: 'Demo versiya: sahifadagi raqamlar demo bazadan olinadi.',
  },
};

const en: LandingCopy = {
  meta: { title: `${B} — every charger in Uzbekistan, one app` },
  nav: {
    drivers: 'Drivers', business: 'Fleets', operators: 'Operators', pricing: 'Pricing',
    compare: 'Compare', faq: 'FAQ', map: 'Network', join: 'Join', demo: 'Open demo', download: 'Download', menu: 'Menu', close: 'Close',
  },
  hero: {
    badge: 'National charging network · MVP launch — Q4 2026',
    title: ['Every charger', 'in Uzbekistan.', 'One app.'],
    sub: 'Find free chargers from every operator, start charging from your phone and pay with Payme or Click. 30% cheaper at night.',
    primary: 'Try the demo',
    secondary: 'How it works',
    live: 'Live · demo network',
    stations: 'stations',
    connectors: 'connectors',
    online: 'online',
    energy: 'kWh today',
    scroll: 'Scroll',
  },
  cities: {
    tashkent: 'Tashkent', samarkand: 'Samarkand', bukhara: 'Bukhara', khiva: 'Khiva', nukus: 'Nukus',
    namangan: 'Namangan', andijan: 'Andijan', fergana: 'Fergana', navoi: 'Navoi', karshi: 'Karshi',
    termez: 'Termez', jizzakh: 'Jizzakh', gulistan: 'Gulistan', kokand: 'Kokand', urgench: 'Urgench',
  },
  strip: { pay: 'Payments', standards: 'Standards', langs: 'Languages' },
  problem: {
    kicker: 'The problem',
    title: 'Today every network has its own app.',
    sub: 'An EV driver in Uzbekistan keeps several apps on their phone, can’t tell if a charger is free until they arrive, and pays differently on every network.',
    items: [
      { n: '5+', t: 'apps', d: 'to install just to see every major network in the country' },
      { n: '?', t: 'is it free', d: 'you often learn a connector’s status only on arrival' },
      { n: '0', t: 'shared queues', d: 'first to arrive gets to charge — no rules at all' },
    ],
    answer: `${B} brings every network into one map, one wallet and one queue.`,
  },
  how: {
    kicker: 'How it works',
    title: 'Three steps and you’re charging.',
    steps: [
      { t: 'Find', d: 'The map shows chargers from every operator and the live status of each connector: free, busy or under maintenance.' },
      { t: 'Plug in', d: 'Connect the cable and tap Start in the app — or book a connector in advance so nobody takes it.' },
      { t: 'Pay', d: 'You pay from your wallet for the kWh you actually used. Receipts, history and CO₂ saved live in your profile.' },
    ],
  },
  features: {
    kicker: 'Features',
    title: 'Everything a driver needs. Including what others don’t have.',
    sub: 'Every feature below already works in the demo — open the Driver App and see for yourself.',
    items: [
      { id: 'map', t: 'Live map of every network', d: 'Each connector’s status updates in real time, no reloads.' },
      { id: 'queue', t: 'A fair queue', d: 'All connectors busy? Join the queue — the next free one is held for you for 5 minutes.' },
      { id: 'book', t: 'Booking', d: '10 minutes to 24 hours ahead. 15 minutes to arrive, 2,000 UZS fee.' },
      { id: 'green', t: 'Green hours', d: '×0.7 at night, ×0.9 by day, ×1.25 at evening peak. The rate locks when you start.' },
      { id: 'trip', t: 'Trip planner', d: 'Intercity routes with charging stops planned for your car.' },
      { id: 'wallet', t: 'Payme & Click', d: 'Your wallet is topped up only once the payment provider confirms.' },
      { id: 'push', t: 'Push notifications', d: 'Charging done, your turn in the queue, booking about to expire — we’ll tell you.' },
      { id: 'eco', t: 'Eco profile', d: 'CO₂ saved in trees and kilometres, achievements and a leaderboard.' },
      { id: 'report', t: 'One-tap reports', d: 'Broken connector? The alert goes straight to that station’s operator.' },
      { id: 'lang', t: 'UZ · RU · EN', d: 'Fully in three languages. Works offline as an app (PWA).' },
    ],
  },
  network: {
    kicker: 'Network now',
    title: 'Live data, straight from the chargers.',
    sub: 'Connector statuses stream from the server in real time. Start a charge in the demo and see it here a second later.',
    filters: { all: 'All', free: 'Has free', fast: 'Fast DC' },
    freeOf: 'free',
    perKwh: 'UZS/kWh',
    feed: 'Live feed',
    empty: 'All quiet. Start charging in the Driver App and the event shows up here.',
    ev: { start: 'Charging started', stop: 'Connector freed', reserved: 'Connector booked', offline: 'Connector offline' },
    status: { available: 'free', occupied: 'busy', reserved: 'booked', unavailable: 'offline' },
    open: 'Charge here',
    none: 'No chargers match this filter.',
    meta: 'One EV charging platform for Uzbekistan: chargers from every operator, Payme and Click payments, queues and booking.',
  },
  green: {
    kicker: 'Green hours',
    title: 'Charge at night — pay 30% less.',
    sub: 'The rate depends on the hour in Tashkent and locks when you start. The chart below is live server data.',
    now: 'Now',
    best: 'Cheapest window',
    in: 'in',
    h: 'h',
    active: 'on now',
    bands: { green: 'Night ×0.7', day: 'Day ×0.9', standard: 'Standard ×1.0', peak: 'Peak ×1.25' },
  },
  calc: {
    kicker: 'Calculator',
    title: 'How much an EV saves you.',
    sub: 'Enter your mileage. Prices are estimates you can change.',
    car: 'Car',
    km: 'Distance per month, km',
    petrol: 'Petrol, UZS/l',
    kwh: 'Charging, UZS/kWh',
    night: 'Charge at night',
    evMonth: 'Electricity per month',
    petrolMonth: 'Petrol per month',
    save: 'Saved per year',
    full: 'Full charge',
    range: 'Range',
    sum: 'UZS',
    km_: 'km',
    note: 'Petrol car at 8 l/100 km. EV consumption and battery are average rated figures; higher on the highway and in winter.',
  },
  compare: {
    kicker: 'Compare',
    title: 'Why not just a network’s own app.',
    sub: 'We compare against typical kinds of apps, not specific companies.',
    cols: [B, 'Single-network app', 'Map aggregator'],
    rows: [
      { t: 'Chargers from every operator in the country', v: [2, 0, 2] },
      { t: 'Start and pay for charging in the app', v: [2, 2, 0] },
      { t: 'Live status of every connector', v: [2, 2, 1] },
      { t: 'Connector booking', v: [2, 1, 0] },
      { t: 'Shared queue at the station', v: [2, 0, 0] },
      { t: 'Night rate and when-it’s-cheaper hints', v: [2, 0, 0] },
      { t: 'Intercity route with stops', v: [2, 1, 2] },
      { t: 'Payme and Click', v: [2, 1, 0] },
      { t: 'Corporate fleet console', v: [2, 0, 0] },
      { t: 'Open API and webhooks for partners', v: [2, 0, 1] },
      { t: 'Fully in Uzbek, Russian and English', v: [2, 1, 1] },
    ],
    legend: ['yes', 'partly', 'no'],
  },
  audiences: {
    kicker: 'Platform',
    title: 'One system for everyone in the market.',
    sub: 'Six apps share one database and sync instantly: what a driver does, the operator, the company and the admin see at once.',
    open: 'Open demo',
    tabs: [
      {
        id: 'driver', label: 'Drivers', title: 'Driver App', portal: 'driver',
        d: 'A mobile app for iOS and Android: map, charging, queue, booking, wallet, trips.',
        points: ['SMS sign-in', 'Every network on one map, with filters', 'Remote start and stop', 'History and receipts', 'Eco profile and achievements'],
      },
      {
        id: 'business', label: 'Fleets', title: 'Business Portal', portal: 'business',
        d: 'For taxi, delivery and corporate fleets: one account for every car and limits per employee.',
        points: ['Cars and drivers', 'Limits by amount and kWh', 'Spend by car and department', 'CSV and PDF reports', 'Two-factor sign-in'],
      },
      {
        id: 'operator', label: 'Operators', title: 'Operator Portal', portal: 'operator',
        d: 'For charger owners: connect over OCPP and reach drivers across the whole country.',
        points: ['OCPP 1.6-J out of the box', 'Live stations, connectors, sessions', 'Tariffs and green hours', 'Alerts and driver reports', 'Finance and payouts'],
      },
      {
        id: 'api', label: 'Developers', title: 'Partner API', portal: 'api',
        d: 'REST API, HMAC-signed webhooks and a sandbox — for malls, hotels, navigation apps and car dealers.',
        points: ['Docs and sandbox', 'Webhooks with retries', 'Delivery log', 'Keys and permissions', 'Test mode'],
      },
    ],
    admin: 'Plus the Admin Control Center — national monitoring, payments, fraud and audit.',
  },
  route: {
    kicker: 'Trips',
    title: 'Tashkent → Khiva without range anxiety.',
    sub: 'A sample Silk Road route in a Zeekr 001. The planner picks the chargers and charging times for you.',
    stops: [
      { city: 'Tashkent', km: 0, note: 'Start · 100%' },
      { city: 'Samarkand', km: 305, note: 'Charge 20 min' },
      { city: 'Bukhara', km: 575, note: 'Charge 35 min' },
      { city: 'Khiva', km: 1020, note: 'Arrive · 20%' },
    ],
    total: 'about 1,020 km · 2 stops',
  },
  security: {
    kicker: 'Trust',
    title: 'Your money and data, protected.',
    items: [
      { t: 'Passwords and 2FA', d: 'Passwords are stored as scrypt hashes. Two-factor sign-in works with Google Authenticator.' },
      { t: 'We never see your card', d: 'Cards are entered on Payme’s or Click’s side. Your wallet is topped up only after they confirm.' },
      { t: 'SMS codes', d: 'Codes are stored hashed, expire in 5 minutes and allow 5 attempts. Numbers are rate-limited.' },
      { t: 'Signed webhooks', d: 'Every partner event is signed with HMAC-SHA256; internal addresses are blocked.' },
      { t: 'Separate access', d: 'Each portal has its own sign-in. Operators see only their network, companies only their fleet.' },
      { t: 'Data in Uzbekistan', d: 'By launch — servers in Uzbekistan, as the personal data law requires.' },
    ],
  },
  roadmap: {
    kicker: 'Roadmap',
    title: 'From MVP to all of Central Asia.',
    done: 'Done',
    items: [
      { when: 'September 2026', t: 'Platform', d: 'Six portals, OCPP 1.6-J, Payme and Click, SMS sign-in, push.', done: true },
      { when: 'Q4 2026', t: 'MVP launch', d: 'Tashkent, first operators, App Store and Google Play.' },
      { when: 'Q1 2027', t: 'M-37 highway', d: 'Tashkent — Samarkand — Bukhara, corporate fleets.' },
      { when: 'Q2 2027', t: 'Roaming', d: 'OCPP 2.0.1 and OCPI 2.3: one account on every network without separate contracts.' },
      { when: 'H2 2027', t: 'Plug & Charge', d: 'ISO 15118: plug in and charging starts and pays by itself.' },
      { when: '2028', t: 'Central Asia', d: 'Kazakhstan, Kyrgyzstan, Tajikistan — one account for the whole region.' },
    ],
  },
  app: {
    kicker: 'The app',
    title: 'Coming soon to the App Store and Google Play.',
    sub: 'Meanwhile, open the full demo right in your browser — it runs on a real server.',
    soon: 'Coming soon',
    web: 'Open in browser',
  },
  join: {
    kicker: 'Join',
    title: 'Be with us from day one.',
    sub: 'Leave your contact — drivers hear about the launch first; operators and companies get a call back within a working day.',
    tabs: { driver: 'Drivers', operator: 'Charger operators', fleet: 'Fleets', partner: 'Partners' },
    pitch: {
      driver: 'Be among the first to hear about the launch, with early access to the app.',
      operator: 'Connect your chargers over OCPP 1.6-J and reach drivers across the country.',
      fleet: 'One account for every car and limits per driver — we’ll walk you through moving your fleet.',
      partner: 'Malls, hotels, car dealers, navigation apps — charging at your venue or inside your app.',
    },
    name: 'Name',
    phone: 'Phone',
    company: 'Company',
    city: 'City',
    size: { operator: 'How many chargers', fleet: 'How many cars', partner: 'What you offer' },
    message: 'Comment',
    optional: 'optional',
    consent: 'I agree to the processing of my personal data under the',
    consentLink: 'privacy policy',
    submit: { driver: 'Tell me at launch', other: 'Send request' },
    sending: 'Sending…',
    done: 'Thank you! Request received.',
    doneDriver: 'We’ll text you on launch day.',
    doneOther: 'We’ll call you back within a working day.',
    again: 'Send another',
    already: 'This number is already on the list — we’ll be in touch.',
    errors: { phone: 'Enter the number as +998 XX XXX XX XX', name: 'Enter your name', company: 'Enter your company', consent: 'Consent to data processing is required', rate: 'Too many requests — try again in a few minutes', generic: 'Couldn’t send — check your connection and try again' },
  },
  legal: {
    privacy: 'Privacy policy', terms: 'Terms of use', offer: 'Public offer',
    title: 'Documents', back: 'Back to home', updated: 'Version of',
    draft: 'Draft. This document is being prepared for publication and reviewed by a lawyer — until then it is not in force.',
    ruOnly: 'This document is currently in Russian. An English version will be added before publication.',
  },
  faq: {
    kicker: 'FAQ',
    title: 'Frequently asked questions.',
    items: [
      { q: `What is ${B}?`, a: `${B} is a single EV charging platform for Uzbekistan. We don’t build our own chargers — we bring different operators’ networks into one app, so the map, starting, paying and queuing work the same everywhere.` },
      { q: 'How much does charging cost?', a: 'The station operator sets the base price per kWh and you see it before you start. At night (23:00–07:00) it’s ×0.7, by day ×0.9 and at evening peak ×1.25 — the multiplier locks when charging starts.' },
      { q: 'How do I pay?', a: 'Top up your wallet through Payme or Click — with Humo, Uzcard or any card they accept. Money arrives only after the payment is confirmed, and charging is billed for the kWh you used.' },
      { q: 'What if every connector is busy?', a: 'Join the queue in the app. When a connector frees up we hold it for you for 5 minutes and send a notification — no other driver can take it.' },
      { q: 'Can I book a connector in advance?', a: 'Yes, from 10 minutes to 24 hours ahead. You get 15 minutes to arrive and the booking fee is 2,000 UZS. Unused bookings expire on their own.' },
      { q: 'Will my car work?', a: 'The app shows each connector’s type and power, and a filter keeps only compatible chargers. For trips, the planner uses your model’s battery and consumption.' },
      { q: 'I own chargers. How do I join?', a: 'Chargers connect over OCPP 1.6-J, the standard most chargers speak. You get an operator console: sessions, tariffs, alerts, finance. Drivers across the country see your chargers right away.' },
      { q: 'Do you have something for companies?', a: 'The Business Portal: one account for every car, limits per employee by amount and kWh, and spend reports in CSV and PDF.' },
      { q: 'When do you launch?', a: 'The MVP launch in Tashkent is planned for Q4 2026. A demo with every feature already runs — you can open it from this page.' },
    ],
  },
  cta: {
    title: 'Try it right now.',
    sub: 'The demo runs on a real server: start charging in the Driver App and watch it appear on the operator’s screen.',
    button: 'Open demo',
    compare: 'Two portals side by side',
  },
  phone: { free: 'free', start: 'Start charging', charging: 'Charging', added: 'kWh', cost: 'UZS', left: 'min to 80%', near: 'Near you', kw: 'kW' },
  footer: {
    about: 'One EV charging platform. Made in Uzbekistan.',
    product: 'Product',
    platform: 'Platform',
    company: 'Company',
    links: {
      drivers: 'Drivers', business: 'Fleets', operators: 'Operators', api: 'Partner API',
      arch: 'Architecture', roadmap: 'Roadmap', security: 'Security', faq: 'FAQ', contact: 'Contact',
    },
    rights: 'All rights reserved.',
    demo: 'Demo version: numbers on this page come from the demo database.',
  },
};

export const COPY: Record<Lang, LandingCopy> = { ru, uz, en };

/** EVs common in Uzbekistan; battery kWh, consumption kWh/100 km (rated, approximate). */
export const CARS = [
  { id: 'song', name: 'BYD Song Plus EV', battery: 71.8, use: 17.5 },
  { id: 'han', name: 'BYD Han EV', battery: 85.4, use: 16.5 },
  { id: 'seagull', name: 'BYD Seagull', battery: 38.9, use: 11.5 },
  { id: 'zeekr', name: 'Zeekr 001', battery: 100, use: 18 },
  { id: 'modely', name: 'Tesla Model Y LR', battery: 75, use: 16.9 },
  { id: 'c11', name: 'Leapmotor C11', battery: 69.9, use: 17.5 },
];
